# Generated by Django 5.2.4 on 2025-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название проекта"),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2018-2019", "2018–2019"),
                            ("2019-2020", "2019–2020"),
                            ("2020-2021", "2020–2021"),
                            ("2021-2022", "2021–2022"),
                            ("2022-2023", "2022–2023"),
                            ("2023-2024", "2023–2024"),
                            ("2024-2025", "2024–2025"),
                            ("2025-2026", "2025–2026"),
                            ("2026-2027", "2026–2027"),
                            ("2027-2028", "2027–2028"),
                        ],
                        max_length=9,
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("social", "Социальный"),
                            ("personal", "Персональный"),
                            ("ivr", "ИВР"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Тип проекта",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Автор проекта"),
                ),
                (
                    "supervisor",
                    models.CharField(max_length=255, verbose_name="Супервайзер"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "Минимальный"),
                            ("basic", "Базовый"),
                            ("high", "Высокий"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Уровень проекта",
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        choices=[
                            ("school", "Школьный"),
                            ("city", "Городской"),
                            ("regional", "Региональный"),
                            ("national", "Всероссийский"),
                        ],
                        default="",
                        max_length=15,
                        verbose_name="Масштаб проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
