# Generated by Django 5.2.4 on 2025-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="customer",
            field=models.CharField(
                choices=[
                    ("Inner", "Внутренний"),
                    ("Outer", "Внешний"),
                    ("Not stated", "Не указано"),
                ],
                default=("Not stated", "Не указано"),
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="perspectives",
            field=models.CharField(
                choices=[("Yes", "Да"), ("No", "Нет")],
                default=("No", "Нет"),
                verbose_name="Наличие перспектив",
            ),
        ),
    ]
